### ISSUE TITLE
About this project

### ISSUE THREAD

**Issue by Askmewho** [M-HT/SR#14]
Hi, a linux arm devoted here.

Time has past since notaz did similar stuff with diablo 2 and StarCraft. Why you picked those games? you have generic tools to to this? Are you planning to expand the list? Any tutorial on how to use it? 

Thanks.

**Comment by M-HT** [comment]
First of all, notaz and his work on Diablo2 and StarCraft has nothing to do with this project - he has [his own project and tools](https://github.com/notaz/ia32rtools).

I chose the games in this project because I like them and I wanted to play them on arm platforms - first [GP2X](https://en.wikipedia.org/wiki/Gp2x) and later [Pandora](https://en.wikipedia.org/wiki/Pandora_(console)).

The tools are generic, but each game requires a lot of specific work, which is why there's no tutorial.

New games might be added, but don't expect anything.
